<a href="https://colab.research.google.com/github/com0040/README_example_Source/blob/main/37_%EC%9D%B8%ED%84%B0%EB%84%B7%EC%97%90_%EC%9E%88%EB%8A%94_%ED%91%9C%EB%A5%BC_%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84%EC%9C%BC%EB%A1%9C_%EB%B0%94%EB%A1%9C_%EB%A7%8C%EB%93%9C%EB%8A%94_%EB%B0%A9%EB%B2%95%09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

In [14]:
url = requests.get('https://finance.naver.com/sise/sise_market_sum.naver?&page=1')
html =  BeautifulSoup(url.text)

table = html.find('table',class_='type_2')
table = pd.read_html(str(table))[0] # -> 리스트안에 데이터에서 [0]번째 데이터를 뽑아온다 - 데이터프레임으로
# -> 누락값이 보인다(실선을 읽어와서)
table = table[table['종목명'].notnull()] # 종목명이 누락값이 아닌 것을 가져온다다

del table['N']
del table['토론실'] # 필요없는 열 삭제

table

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE
1,삼성전자,56200.0,1000.0,+1.81%,100.0,3355018.0,5969783.0,49.51,6412780.0,8.52,13.92
2,LG에너지솔루션,488500.0,11500.0,+2.41%,500.0,1143090.0,234000.0,4.49,112122.0,811.46,10.68
3,SK하이닉스,95200.0,300.0,+0.32%,5000.0,693058.0,728002.0,50.72,1656583.0,6.04,16.84
4,삼성바이오로직스,806000.0,1000.0,-0.12%,2500.0,573662.0,71174.0,10.50,26955.0,107.20,8.21
5,삼성전자우,50900.0,500.0,+0.99%,100.0,418849.0,822887.0,71.60,441157.0,7.72,NaN
9,삼성SDI,604000.0,8000.0,+1.34%,5000.0,415338.0,68765.0,45.12,66677.0,28.18,8.45
10,LG화학,584000.0,9000.0,+1.57%,5000.0,412259.0,70592.0,48.37,84539.0,20.59,18.47
11,현대차,167500.0,3000.0,+1.82%,5000.0,357894.0,213668.0,28.96,257987.0,7.43,6.84
12,기아,69500.0,1200.0,+1.76%,5000.0,281728.0,405363.0,37.18,464791.0,5.32,14.69
13,NAVER,167500.0,9000.0,+5.68%,100.0,274782.0,164049.0,50.03,809813.0,27.32,106.72
17,셀트리온,173000.0,8000.0,+4.85%,1000.0,243570.0,140792.0,21.31,212175.0,43.28,16.04
18,카카오,51000.0,3700.0,+7.82%,100.0,227114.0,445322.0,28.12,2572930.0,10.20,17.10
19,삼성물산,110500.0,3500.0,+3.27%,100.0,206510.0,186887.0,16.52,97756.0,13.16,5.40
20,POSCO홀딩스,243000.0,5500.0,+2.32%,5000.0,205508.0,84571.0,53.63,165232.0,2.93,13.97
21,KB금융,46750.0,2050.0,+4.59%,5000.0,191159.0,408897.0,73.67,601229.0,4.13,9.80
25,현대모비스,197000.0,1500.0,+0.77%,5000.0,186309.0,94573.0,35.69,93777.0,7.86,6.87
26,신한지주,36000.0,1100.0,+3.15%,5000.0,184656.0,512934.0,61.74,589903.0,4.47,8.80
27,SK,209000.0,9500.0,+4.76%,200.0,154972.0,74149.0,22.36,57019.0,4.69,10.19
28,SK이노베이션,158000.0,6500.0,+4.29%,5000.0,146096.0,92466.0,25.75,224957.0,5.78,1.91
29,LG전자,81200.0,3100.0,+3.97%,5000.0,132882.0,163648.0,25.84,265463.0,7.97,6.32
33,삼성생명,65700.0,300.0,+0.46%,500.0,131400.0,200000.0,13.12,83496.0,18.00,4.01
34,포스코케미칼,161500.0,3000.0,+1.89%,500.0,125103.0,77463.0,7.45,317874.0,91.24,7.92
35,LG,77900.0,1300.0,+1.70%,5000.0,122537.0,157301.0,36.20,68763.0,5.35,12.36
36,고려아연,614000.0,10000.0,+1.66%,5000.0,121960.0,19863.0,21.75,21297.0,13.60,11.07
37,KT&G,87300.0,100.0,+0.11%,5000.0,119856.0,137292.0,42.30,97980.0,11.32,10.74
41,하나금융지주,38450.0,950.0,+2.53%,5000.0,113775.0,295903.0,71.17,529740.0,3.29,10.86
42,한국전력,17400.0,150.0,+0.87%,5000.0,111702.0,641964.0,14.69,636354.0,-0.72,-7.99
43,SK텔레콤,49950.0,1400.0,+2.88%,100.0,109307.0,218833.0,46.57,166947.0,8.61,13.63
44,현대중공업,117000.0,1500.0,+1.30%,5000.0,103865.0,88773.0,5.66,104081.0,-14.06,-14.87
45,S-Oil,85800.0,3800.0,+4.63%,2500.0,96596.0,112583.0,81.54,194843.0,3.99,21.76
49,삼성화재,193500.0,5500.0,+2.93%,500.0,91670.0,47375.0,49.90,26930.0,8.48,7.09
50,HMM,18700.0,550.0,+3.03%,5000.0,91450.0,489039.0,9.44,1128571.0,0.78,88.62
51,LG생활건강,582000.0,19000.0,+3.37%,5000.0,90898.0,15618.0,37.45,32566.0,17.28,16.65
52,한화솔루션,47300.0,1900.0,+4.19%,5000.0,90475.0,191278.0,22.64,766001.0,26.03,8.79
53,KT,34550.0,650.0,+1.92%,5000.0,90214.0,261112.0,44.38,282874.0,6.27,9.36
57,크래프톤,183500.0,7500.0,+4.26%,100.0,90047.0,49072.0,29.25,123148.0,14.26,17.86
58,삼성에스디에스,115000.0,2000.0,+1.77%,500.0,88984.0,77378.0,13.60,38178.0,11.70,8.80
59,삼성전기,118500.0,4500.0,+3.95%,5000.0,88512.0,74694.0,26.32,141855.0,8.91,14.29
60,우리금융지주,11650.0,300.0,+2.64%,5000.0,84819.0,728061.0,40.50,1277856.0,2.89,10.59
61,카카오뱅크,17750.0,1200.0,+7.25%,5000.0,84602.0,476631.0,13.16,3541336.0,39.36,4.91
65,두산에너빌리티,13100.0,500.0,+3.97%,5000.0,83618.0,638308.0,11.70,2926690.0,98.50,10.67
66,대한항공,21050.0,350.0,+1.69%,5000.0,77510.0,368221.0,14.75,915906.0,4.92,11.60
67,기업은행,10200.0,230.0,+2.31%,5000.0,75919.0,744301.0,13.44,575405.0,3.35,9.21
68,엔씨소프트,335500.0,13000.0,+4.03%,500.0,73656.0,21954.0,43.17,55046.0,14.47,12.62
69,LG이노텍,291500.0,11500.0,+4.11%,5000.0,68990.0,23667.0,24.76,122409.0,7.16,30.94
73,현대글로비스,170500.0,8000.0,+4.92%,500.0,63938.0,37500.0,46.35,57946.0,6.18,14.41
74,CJ제일제당,396500.0,8000.0,+2.06%,5000.0,59690.0,15054.0,24.48,5801.0,10.01,10.76
75,아모레퍼시픽,100500.0,5600.0,+5.90%,500.0,58785.0,58493.0,25.61,164137.0,82.58,4.20
76,롯데케미칼,164500.0,9000.0,+5.79%,5000.0,56383.0,34275.0,23.95,65698.0,10.97,9.87
77,SK바이오사이언스,72800.0,600.0,+0.83%,500.0,55899.0,76784.0,4.04,153468.0,16.67,38.08

In [7]:
html.find('td',class_='pgRR') # 태그 : td, 클래스속성값 : pgRR

<td class="pgRR">
<a href="/sise/sise_market_sum.naver?&amp;page=38">맨뒤
				<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
</a>
</td>

In [6]:
html.find('td',class_='pgRR').find('a') # 태그 : td, 클래스속성값 : pgRR --> 안에서 a

<a href="/sise/sise_market_sum.naver?&amp;page=38">맨뒤
				<img alt="" border="0" height="5" src="https://ssl.pstatic.net/static/n/cmn/bu_pgarRR.gif" width="8"/>
</a>

In [8]:
 # 38을 가져오려면 href에 접근
 html.find('td',class_='pgRR').find('a')['href'] # 태그 : td, 클래스속성값 : pgRR --> 안에서 a

'/sise/sise_market_sum.naver?&page=38'

In [9]:
# =을 기준으로 자를 것
html.find('td',class_='pgRR').find('a')['href'].split('=')

['/sise/sise_market_sum.naver?&page', '38']

In [12]:
# -1번째
kospi_page = html.find('td',class_='pgRR').find('a')['href'].split('=')[-1]
kospi_page

'38'

In [16]:
# -1번째
kospi_page = int(html.find('td',class_='pgRR').find('a')['href'].split('=')[-1])
kospi_page

38

In [17]:
url = requests.get('https://finance.naver.com/sise/sise_market_sum.naver?&page=1')
html =  BeautifulSoup(url.text)
kospi_page = int(html.find('td',class_='pgRR').find('a')['href'].split('=')[-1])

total =[]

for n in range(1,kospi_page+1):
    # n페이지를 가져오기
    url = requests.get('https://finance.naver.com/sise/sise_market_sum.naver?&page={}'.format(n)) # 요청
    html =  BeautifulSoup(url.text) # 번역 

    table = html.find('table',class_='type_2') # 테이블 찾고 
    table = pd.read_html(str(table))[0] # -> 리스트안에 데이터에서 [0]번째 데이터를 뽑아온다 - 데이터프레임으로
    # -> 누락값이 보인다(실선을 읽어와서)
    table = table[table['종목명'].notnull()] # 종목명이 누락값이 아닌 것을 가져온다

    del table['N']
    del table['토론실'] # 필요없는 열 삭제

    total.append(table)
    time.sleep(1)

    print('{} 페이지 저장완료...'.format(len(total)))

1 페이지 저장완료...
2 페이지 저장완료...
3 페이지 저장완료...
4 페이지 저장완료...
5 페이지 저장완료...
6 페이지 저장완료...
7 페이지 저장완료...
8 페이지 저장완료...
9 페이지 저장완료...
10 페이지 저장완료...
11 페이지 저장완료...
12 페이지 저장완료...
13 페이지 저장완료...
14 페이지 저장완료...
15 페이지 저장완료...
16 페이지 저장완료...
17 페이지 저장완료...
18 페이지 저장완료...
19 페이지 저장완료...
20 페이지 저장완료...
21 페이지 저장완료...
22 페이지 저장완료...
23 페이지 저장완료...
24 페이지 저장완료...
25 페이지 저장완료...
26 페이지 저장완료...
27 페이지 저장완료...
28 페이지 저장완료...
29 페이지 저장완료...
30 페이지 저장완료...
31 페이지 저장완료...
32 페이지 저장완료...
33 페이지 저장완료...
34 페이지 저장완료...
35 페이지 저장완료...
36 페이지 저장완료...
37 페이지 저장완료...
38 페이지 저장완료...

In [18]:
len(total)

38

In [20]:
total[0] # 1페이지

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE
1,삼성전자,56200.0,1000.0,+1.81%,100.0,3355018.0,5969783.0,49.51,6458351.0,8.52,13.92
2,LG에너지솔루션,488500.0,11500.0,+2.41%,500.0,1143090.0,234000.0,4.49,115040.0,811.46,10.68
3,SK하이닉스,95200.0,300.0,+0.32%,5000.0,693058.0,728002.0,50.72,1665252.0,6.04,16.84
4,삼성바이오로직스,806000.0,1000.0,-0.12%,2500.0,573662.0,71174.0,10.50,27570.0,107.20,8.21
5,삼성전자우,50900.0,500.0,+0.99%,100.0,418849.0,822887.0,71.60,450046.0,7.72,NaN
9,삼성SDI,605000.0,9000.0,+1.51%,5000.0,416025.0,68765.0,45.12,67343.0,28.22,8.45
10,LG화학,583000.0,8000.0,+1.39%,5000.0,411553.0,70592.0,48.37,88446.0,20.55,18.47
11,현대차,167500.0,3000.0,+1.82%,5000.0,357894.0,213668.0,28.96,263235.0,7.43,6.84
12,기아,69700.0,1400.0,+2.05%,5000.0,282538.0,405363.0,37.18,474747.0,5.33,14.69
13,NAVER,166500.0,8000.0,+5.05%,100.0,273142.0,164049.0,50.03,827658.0,27.16,106.72
17,셀트리온,173000.0,8000.0,+4.85%,1000.0,243570.0,140792.0,21.31,215853.0,43.28,16.04
18,카카오,50700.0,3400.0,+7.19%,100.0,225778.0,445322.0,28.12,2614929.0,10.14,17.10
19,삼성물산,111000.0,4000.0,+3.74%,100.0,207445.0,186887.0,16.52,99521.0,13.22,5.40
20,POSCO홀딩스,244000.0,6500.0,+2.74%,5000.0,206354.0,84571.0,53.63,172880.0,2.94,13.97
21,KB금융,46800.0,2100.0,+4.70%,5000.0,191364.0,408897.0,73.67,610937.0,4.13,9.80
25,현대모비스,197000.0,1500.0,+0.77%,5000.0,186309.0,94573.0,35.69,94502.0,7.86,6.87
26,신한지주,35900.0,1000.0,+2.87%,5000.0,184143.0,512934.0,61.74,607285.0,4.46,8.80
27,SK,209500.0,10000.0,+5.01%,200.0,155343.0,74149.0,22.36,59268.0,4.70,10.19
28,SK이노베이션,157500.0,6000.0,+3.96%,5000.0,145633.0,92466.0,25.75,228027.0,5.76,1.91
29,LG전자,81200.0,3100.0,+3.97%,5000.0,132882.0,163648.0,25.84,267423.0,7.97,6.32
33,삼성생명,65800.0,400.0,+0.61%,500.0,131600.0,200000.0,13.12,87258.0,18.03,4.01
34,포스코케미칼,161500.0,3000.0,+1.89%,500.0,125103.0,77463.0,7.45,320747.0,91.24,7.92
35,고려아연,619000.0,15000.0,+2.48%,5000.0,122953.0,19863.0,21.75,24203.0,13.71,11.07
36,LG,77800.0,1200.0,+1.57%,5000.0,122380.0,157301.0,36.20,70334.0,5.35,12.36
37,KT&G,87300.0,100.0,+0.11%,5000.0,119856.0,137292.0,42.30,100300.0,11.32,10.74
41,하나금융지주,38450.0,950.0,+2.53%,5000.0,113775.0,295903.0,71.17,551719.0,3.29,10.86
42,한국전력,17350.0,100.0,+0.58%,5000.0,111381.0,641964.0,14.69,647548.0,-0.72,-7.99
43,SK텔레콤,49850.0,1300.0,+2.68%,100.0,109088.0,218833.0,46.57,171258.0,8.59,13.63
44,현대중공업,117500.0,2000.0,+1.73%,5000.0,104308.0,88773.0,5.66,104620.0,-14.12,-14.87
45,S-Oil,85800.0,3800.0,+4.63%,2500.0,96596.0,112583.0,81.54,196232.0,3.99,21.76
49,HMM,18800.0,650.0,+3.58%,5000.0,91939.0,489039.0,9.44,1171333.0,0.79,88.62
50,삼성화재,193000.0,5000.0,+2.66%,500.0,91433.0,47375.0,49.90,27611.0,8.46,7.09
51,LG생활건강,581000.0,18000.0,+3.20%,5000.0,90742.0,15618.0,37.45,33406.0,17.25,16.65
52,한화솔루션,47250.0,1850.0,+4.07%,5000.0,90379.0,191278.0,22.64,784689.0,26.00,8.79
53,KT,34550.0,650.0,+1.92%,5000.0,90214.0,261112.0,44.38,291103.0,6.27,9.36
57,크래프톤,183500.0,7500.0,+4.26%,100.0,90047.0,49072.0,29.25,125194.0,14.26,17.86
58,삼성에스디에스,116000.0,3000.0,+2.65%,500.0,89758.0,77378.0,13.60,40200.0,11.80,8.80
59,삼성전기,118000.0,4000.0,+3.51%,5000.0,88139.0,74694.0,26.32,142564.0,8.88,14.29
60,우리금융지주,11650.0,300.0,+2.64%,5000.0,84819.0,728061.0,40.50,1286065.0,2.89,10.59
61,두산에너빌리티,13150.0,550.0,+4.37%,5000.0,83938.0,638308.0,11.70,2967819.0,98.87,10.67
65,카카오뱅크,17600.0,1050.0,+6.34%,5000.0,83887.0,476631.0,13.16,3628254.0,39.02,4.91
66,대한항공,21100.0,400.0,+1.93%,5000.0,77695.0,368221.0,14.75,955353.0,4.93,11.60
67,기업은행,10250.0,280.0,+2.81%,5000.0,76291.0,744301.0,13.44,582567.0,3.37,9.21
68,엔씨소프트,335500.0,13000.0,+4.03%,500.0,73656.0,21954.0,43.17,55393.0,14.47,12.62
69,LG이노텍,291000.0,11000.0,+3.93%,5000.0,68871.0,23667.0,24.76,123613.0,7.15,30.94
73,현대글로비스,171000.0,8500.0,+5.23%,500.0,64125.0,37500.0,46.35,58666.0,6.19,14.41
74,CJ제일제당,396500.0,8000.0,+2.06%,5000.0,59690.0,15054.0,24.48,5973.0,10.01,10.76
75,아모레퍼시픽,100500.0,5600.0,+5.90%,500.0,58785.0,58493.0,25.61,165880.0,82.58,4.20
76,롯데케미칼,164500.0,9000.0,+5.79%,5000.0,56383.0,34275.0,23.95,68598.0,10.97,9.87
77,SK바이오사이언스,72700.0,500.0,+0.69%,500.0,55822.0,76784.0,4.04,155964.0,16.65,38.08

In [21]:
kospi =pd.concat(total, ignore_index=True)
kospi

,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE
0,삼성전자,56200.0,1000.0,+1.81%,100.0,3355018.0,5969783.0,49.51,6458351.0,8.52,13.92
1,LG에너지솔루션,488500.0,11500.0,+2.41%,500.0,1143090.0,234000.0,4.49,115040.0,811.46,10.68
2,SK하이닉스,95200.0,300.0,+0.32%,5000.0,693058.0,728002.0,50.72,1665252.0,6.04,16.84
3,삼성바이오로직스,806000.0,1000.0,-0.12%,2500.0,573662.0,71174.0,10.50,27570.0,107.20,8.21
4,삼성전자우,50900.0,500.0,+0.99%,100.0,418849.0,822887.0,71.60,450046.0,7.72,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1864,KBSTAR 모멘텀밸류,11840.0,280.0,+2.42%,0.0,12.0,100.0,0.00,202.0,NaN,NaN
1865,KBSTAR 200에너지화학,9800.0,310.0,+3.27%,0.0,12.0,120.0,0.00,47.0,NaN,NaN
1866,KBSTAR 200생활소비재,5905.0,95.0,+1.64%,0.0,11.0,180.0,0.00,38.0,NaN,NaN
1867,KBSTAR 200산업재,10235.0,285.0,+2.86%,0.0,8.0,80.0,0.00,2.0,NaN,NaN
1868,KBSTAR 200경기소비재,8615.0,155.0,+1.83%,0.0,7.0,80.0,0.00,4.0,NaN,NaN

In [22]:
kospi.to_excel('kospi.xlsx')